name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into Ubuntu Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRO_SERVER_HOST }}
          username: ${{ secrets.PRO_SERVER_USERNAME }}
          password: ${{ secrets.PRO_SERVER_PASSWORD }}
          port: ${{ secrets.PRO_SERVER_PORT }}
          script: |
            cd ~/pnl-software/production/yaly-couture-fe
            git checkout main
            git fetch -p
            git pull
            cd ..
            docker stop yalycouture-frontend || true
            docker rm  yalycouture-frontend || true
            docker rmi production_yalycouture-frontend
            docker compose up -d
