name: Deploy QA

on:
  push:
    branches:
      - QA

jobs:
  deploy_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into Ubuntu Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.QA_SERVER_HOST }}
          username: ${{ secrets.QA_SERVER_USERNAME }}
          password: ${{ secrets.QA_SERVER_PASSWORD }}
          port: ${{ secrets.QA_SERVER_PORT }}
          script: |
            cd ~/pnl-software/qa/yaly-couture-fe
            git checkout QA
            git fetch -p
            git pull
            cd ..
            docker stop dev-yalycouture-frontend || true
            docker rm  dev-yalycouture-frontend || true
            docker rmi qa_dev-yalycouture-frontend
            docker compose up -d
